Add client errors
humans-group/go-apns pull request #2
Opened 2020-11-09 15:38 UTC by karpovicham

# Purpose
Add client errors

# Implementation
- Create and expose `ErrExpiredToken`

2020-11-09 19:42 UTC, mkorolyov requested changes

2020-11-09 19:42 UTC, mkorolyov commented on client.go
> +// Error when the token is stale and a new token should be generated.
```
type Error string

func (e Error) Error() string {
  return string(e)
}

const ErrExpiredToekn Error = "ExpiredProviderToken"
```

2020-11-10 13:26 UTC, karpovicham commented on client.go
> +// Error when the token is stale and a new token should be generated.
Updated

2020-11-10 13:26 UTC, karpovicham commented on client.go
> +		return Error(reason)
Is it fine to return typed error here, or `fmt.Error` should be here?

2020-11-11 09:00 UTC, karpovicham commented on Makefile
> +	easyjson notification.go api.go
just moved code from `response.go` to `api.go` (and Reason to be typed) to make `go-apns` and `go-fcm` structures look similar

2020-11-11 15:27 UTC, karpovicham commented on client.go
> +		return Error(reason)
done with fmt.Error

2020-11-11 17:12 UTC, mkorolyov approved these changes

2020-11-11 17:13 UTC, merged